pring.application.name=SpringBoot-Feeds-Application


#DB
spring.datasource.url=jdbc:mysql://localhost:3306/db_name
spring.datasource.driverClassName=
spring.datasource.username=root
spring.datasource.password=your_pswd
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.path=

#email
spring.mail.host=SMTP
spring.mail.port=574
spring.mail.username=your_email@gmail.com
spring.mail.password=your_email_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true